[workspace]
members = [
	"relay/runtimes/kusama",
	"relay/runtimes/kusama/constants",
	"relay/runtimes/metrics",
	"relay/runtimes/polkadot",
	"relay/runtimes/polkadot/constants",
	"system-parachains/runtimes/asset-hubs/asset-hub-kusama",
	"system-parachains/runtimes/asset-hubs/asset-hub-polkadot",
	"system-parachains/runtimes/bridge-hubs/bridge-hub-kusama",
	"system-parachains/runtimes/bridge-hubs/bridge-hub-polkadot",
	"system-parachains/runtimes/bridge-hubs/bridge-hub-rococo",
	"system-parachains/runtimes/collectives/collectives-polkadot",
]

[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/polkadot-fellows/runtimes.git"
version = "1.0.0"
