name: Verify Changelog

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

jobs:

  verify-changelog-updated:
    name: Verify that Changelog is Updated
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Get Changed Files
        id: changed
        uses: foodee/pr-includes-file-change@master
        with:
          paths: ^CHANGELOG.md
      - name: Set error
        if: steps.changed.outputs.matched != 'true' && !contains(github.event.pull_request.body, '[x] Does not require a CHANGELOG entry')
        run: echo "::error::CHANGELOG.md has not been modified. Either modify the file or check the checkbox in the body" && exit 1

  verify-changelog-valid:
    name: Verify that Changelog is valid
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Verify
        run: .github/changelog-processor.py CHANGELOG.md --validate-changelog
